### ISSUE TITLE
How to output the results?

### ISSUE THREAD

**Issue by allanj** [zwx980624/mwp-cl#2]
Besides just getting the number? how to I get the tree, or final mathematical expression from here? https://github.com/zwx980624/mwp-cl/blob/main/run_ft.py#L218-L248

**Comment by zwx980624** [comment]
You may read the source code of func "compute_prefix_tree_result", which parses and compare the final mathematical expression.

**Comment by allanj** [comment]
Thanks a lot. I think I have printed them out.
